# Generated by Django 6.0.2 on 2026-06-04 11:40

import django.db.models.deletion
import django_hstl.valids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Available'), ('O', 'Occupied'), ('M', 'Maintenance')], default='A', help_text='Current status of the bed', max_length=1, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(help_text='Full Name of the user', max_length=50, validators=[django_hstl.valids.validate_name], verbose_name='Name')),
                ('mobile', models.CharField(help_text='Mobile number of the user', max_length=10, unique=True, validators=[django_hstl.valids.validate_mobile], verbose_name='Mobile')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to disable the user', verbose_name='Allow login?')),
                ('is_staff', models.BooleanField(default=False, help_text='Uncheck to make the user a Student', verbose_name='Is Staff?')),
                ('is_superuser', models.BooleanField(default=False, help_text='Uncheck to make the user a Staff', verbose_name='Is SuperUser?')),
                ('join_date', models.DateField(auto_now_add=True, help_text='The date of joining of the User', verbose_name='Join Date')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Date when the allocation begins', verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='Date when the allocation ends', null=True, verbose_name='End Date')),
                ('status', models.CharField(choices=[('A', 'Active'), ('C', 'Completed'), ('X', 'Cancelled')], default='A', help_text='Current status of the allocation', max_length=1, verbose_name='Status')),
                ('student', models.ForeignKey(help_text='Student allocated to this bed', limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('bed', models.ForeignKey(help_text='Bed allocated to the student', on_delete=django.db.models.deletion.CASCADE, to='django_hstl.bed', verbose_name='Bed')),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the hostel', max_length=100, unique=True, verbose_name='Hostel Name')),
                ('code', models.CharField(help_text='Short code for the hostel (e.g., BH1)', max_length=10, unique=True, verbose_name='Hostel Code')),
                ('gender_type', models.CharField(choices=[('M', 'Boys'), ('F', 'Girls'), ('C', 'Co-ed')], help_text='Allowed gender for this hostel', max_length=1, verbose_name='Gender Type')),
                ('capacity', models.PositiveIntegerField(default=0, help_text='Total student capacity of the hostel', verbose_name='Capacity')),
                ('chief_warden', models.ForeignKey(blank=True, help_text='Staff member managing this hostel', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_hostels', to=settings.AUTH_USER_MODEL, verbose_name='Chief Warden')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('E', 'Electrical'), ('P', 'Plumbing'), ('C', 'Cleaning'), ('I', 'Internet'), ('O', 'Other')], help_text='Category of the complaint', max_length=1, verbose_name='Category')),
                ('description', models.TextField(help_text='Detailed description of the issue', verbose_name='Description')),
                ('status', models.CharField(choices=[('O', 'Open'), ('I', 'In Progress'), ('R', 'Resolved')], default='O', help_text='Current status of the complaint', max_length=1, verbose_name='Status')),
                ('raised_on', models.DateTimeField(auto_now_add=True, help_text='Date and time the complaint was raised', verbose_name='Raised On')),
                ('admin_remarks', models.TextField(blank=True, help_text='Remarks or notes from the administration', null=True, verbose_name='Admin Remarks')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff member assigned to resolve the complaint', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('student', models.ForeignKey(help_text='Student who raised the complaint', on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('hostel', models.ForeignKey(help_text='Hostel where the issue occurred', on_delete=django.db.models.deletion.CASCADE, to='django_hstl.hostel', verbose_name='Hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or description of the invoice', max_length=100, verbose_name='Title')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount due for the invoice', max_digits=10, verbose_name='Amount')),
                ('due_date', models.DateField(help_text='Date by which the invoice must be paid', verbose_name='Due Date')),
                ('status', models.CharField(choices=[('U', 'Unpaid'), ('P', 'Partially Paid'), ('F', 'Fully Paid')], default='U', help_text='Payment status of the invoice', max_length=1, verbose_name='Status')),
                ('student', models.ForeignKey(help_text='Student this invoice belongs to', limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateTimeField(help_text='Date and time of departure', verbose_name='Departure Date')),
                ('return_date', models.DateTimeField(help_text='Expected date and time of return', verbose_name='Return Date')),
                ('reason', models.TextField(help_text='Reason for the leave request', verbose_name='Reason')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', help_text='Current status of the leave request', max_length=1, verbose_name='Status')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Staff member who approved the leave', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('student', models.ForeignKey(help_text='Student requesting the leave', limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid in this transaction', max_digits=10, verbose_name='Amount Paid')),
                ('transaction_id', models.CharField(help_text='Unique identifier for the payment transaction', max_length=100, unique=True, verbose_name='Transaction ID')),
                ('paid_on', models.DateField(auto_now_add=True, help_text='Date when the payment was made', verbose_name='Paid On')),
                ('invoice', models.ForeignKey(help_text='Invoice this payment is applied to', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='django_hstl.invoice', verbose_name='Invoice')),
                ('received_by', models.ForeignKey(help_text='Staff member who received the payment', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Received By')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(help_text='Unique number or identifier for the room', max_length=10, verbose_name='Room Number')),
                ('room_type', models.CharField(choices=[('A1', 'AC Single'), ('N1', 'Non-AC Single'), ('A2', 'AC Double'), ('N2', 'Non-AC Double'), ('A3', 'AC Triple'), ('N3', 'Non-AC Triple'), ('A4', 'AC Quadruple'), ('N4', 'Non-AC Quadruple')], help_text='Type and capacity of the room', max_length=2, verbose_name='Room Type')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the room', max_digits=10, validators=[django_hstl.valids.validate_price], verbose_name='Price')),
                ('hostel', models.ForeignKey(help_text='Hostel this room belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='django_hstl.hostel', verbose_name='Hostel')),
            ],
            options={
                'unique_together': {('hostel', 'room_number')},
            },
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(help_text='Room this bed is located in', on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='django_hstl.room', verbose_name='Room'),
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Gender of the staff member', max_length=1, verbose_name='Gender')),
                ('designation', models.CharField(help_text='Job title or designation of the staff member', max_length=100, verbose_name='Designation')),
                ('shift', models.CharField(blank=True, help_text='Working shift of the staff member', max_length=50, null=True, verbose_name='Shift')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0.0, help_text='Base monthly salary', max_digits=10, verbose_name='Base Salary')),
                ('hire_date', models.DateField(auto_now_add=True, help_text='Date when the staff member was hired', verbose_name='Hire Date')),
                ('auth_id', models.CharField(blank=True, help_text='ID proof of the staff member', max_length=12, null=True, unique=True, validators=[django_hstl.valids.validate_aadhar], verbose_name='Aadhar')),
                ('hostel_assigned', models.ForeignKey(blank=True, help_text='Hostel assigned to this staff member', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_hstl.hostel', verbose_name='Hostel Assigned')),
                ('user', models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Gender of the student', max_length=1, verbose_name='Gender')),
                ('parent_name', models.CharField(help_text='Name of the parent or guardian', max_length=100, validators=[django_hstl.valids.validate_name], verbose_name='Parent Name')),
                ('parent_mobile', models.CharField(help_text='Mobile number of the parent or guardian', max_length=10, validators=[django_hstl.valids.validate_mobile], verbose_name='Parent Mobile')),
                ('blood_group', models.CharField(blank=True, help_text='Blood group of the student', max_length=5, null=True, verbose_name='Blood Group')),
                ('address', models.TextField(help_text='Permanent address of the student', validators=[django_hstl.valids.validate_address], verbose_name='Address')),
                ('course', models.CharField(help_text='Course or program the student is enrolled in', max_length=100, verbose_name='Course')),
                ('auth_id', models.CharField(help_text='ID proof of the user', max_length=12, unique=True, validators=[django_hstl.valids.validate_aadhar], verbose_name='Aadhar')),
                ('user', models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(help_text='Name of the visitor', max_length=100, verbose_name='Visitor Name')),
                ('relation', models.CharField(help_text='Relationship of the visitor to the student', max_length=50, verbose_name='Relation')),
                ('check_in', models.DateTimeField(auto_now_add=True, help_text='Date and time the visitor checked in', verbose_name='Check-In Time')),
                ('check_out', models.DateTimeField(blank=True, help_text='Date and time the visitor checked out', null=True, verbose_name='Check-Out Time')),
                ('logged_by', models.ForeignKey(help_text='Staff member who logged the visitor entry', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_visitors', to=settings.AUTH_USER_MODEL, verbose_name='Logged By')),
                ('student', models.ForeignKey(help_text='Student the visitor is meeting', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField(help_text='Use the 1st of the month to represent the pay period', verbose_name='Month/Year')),
                ('basic_salary', models.DecimalField(decimal_places=2, help_text='Basic salary for the pay period', max_digits=10, verbose_name='Basic Salary')),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, help_text='Total deductions for the pay period', max_digits=10, verbose_name='Deductions')),
                ('net_payable', models.DecimalField(decimal_places=2, help_text='Net amount payable after deductions', max_digits=10, verbose_name='Net Payable')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('D', 'Paid')], default='P', help_text='Payment status of the payroll record', max_length=1, verbose_name='Status')),
                ('paid_on', models.DateField(blank=True, help_text='Date when the payroll was paid', null=True, verbose_name='Paid On')),
                ('staff', models.ForeignKey(help_text='Staff member this payroll record belongs to', limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Staff Member')),
            ],
            options={
                'unique_together': {('staff', 'month_year')},
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the attendance record', verbose_name='Date')),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('HD', 'Half-Day'), ('L', 'On Leave')], help_text='Attendance status for the date', max_length=2, verbose_name='Status')),
                ('time_in', models.TimeField(blank=True, help_text='Time the staff member checked in', null=True, verbose_name='Time In')),
                ('time_out', models.TimeField(blank=True, help_text='Time the staff member checked out', null=True, verbose_name='Time Out')),
                ('staff', models.ForeignKey(help_text='Staff member this attendance record belongs to', limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Staff Member')),
            ],
            options={
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
