# Generated by Django 6.0.2 on 2026-05-08 12:20

import django_hstl.valids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_hstl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='auth_type',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='address',
            field=models.TextField(help_text='Address of the user', max_length=200, validators=[django_hstl.valids.validate_address], verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='auth_id',
            field=models.CharField(help_text='ID proof of the user', max_length=12, unique=True, validators=[django_hstl.valids.validate_aadhar], verbose_name='Aadhar'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to delete the user', verbose_name='Allow login?'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Uncheck to make the user a Student', verbose_name='Is Staff?'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Uncheck to make the user a Staff', verbose_name='Is SuperUser?'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateField(auto_now_add=True, help_text='The date of joining of the User', verbose_name='Join Date'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='mobile',
            field=models.CharField(help_text='Mobile number of the user', max_length=10, unique=True, validators=[django_hstl.valids.validate_mobile], verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(help_text='Full Name of the user', max_length=50, validators=[django_hstl.valids.validate_name], verbose_name='Name'),
        ),
    ]
