# Generated by Django 6.0.2 on 2026-05-13 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_hstl', '0002_remove_myuser_auth_type_alter_myuser_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(help_text='Eg.AS101:A=AC,S=Single', max_length=5, unique=True, verbose_name='Room Number')),
                ('room_type', models.CharField(choices=[('AS', 'AC Single'), ('NS', 'Non-AC Single'), ('AD', 'AC Double'), ('ND', 'Non-AC Double'), ('AT', 'AC Triple'), ('NT', 'Non-AC Triple'), ('AQ', 'AC Quadruple'), ('NQ', 'Non-AC Quadruple')], help_text='Select a room type', max_length=2, verbose_name='Room Type')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the Room', max_digits=10, verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myuser', models.OneToOneField(help_text='...', limit_choices_to={'is_active': True, 'is_staff': False, 'is_superuser': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='StudentID')),
                ('room', models.ForeignKey(help_text='...', on_delete=django.db.models.deletion.CASCADE, to='django_hstl.room', verbose_name='RoomID')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('E', 'Electrical'), ('P', 'Plumbing'), ('C', 'Cleaning'), ('I', 'Internet'), ('O', 'Other')], help_text='Category of the Complaint', max_length=1, verbose_name='Category')),
                ('status', models.CharField(choices=[('O', 'Open'), ('R', 'Resolved'), ('I', 'In Progress')], default='O', help_text='Status of Complaint', max_length=1, verbose_name='Status')),
                ('description', models.TextField(help_text='Please tell us more about issue', verbose_name='Description')),
                ('raised_on', models.DateTimeField(auto_now_add=True, help_text='Ticket raised on', verbose_name='Raised on')),
                ('admin_remarks', models.TextField(blank=True, help_text='Admin remark on Complaint', null=True, verbose_name='Admin Rmarks')),
                ('bed', models.ForeignKey(help_text='...', on_delete=django.db.models.deletion.CASCADE, to='django_hstl.bed', verbose_name='BedID')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Paid'), ('U', 'Pending'), ('O', 'Overdue')], default='U', help_text='Status of the payment', max_length=1, verbose_name='Payment Status')),
                ('paid_date', models.DateField(blank=True, help_text='Date of the payment', null=True, verbose_name='Payment Date')),
                ('bed', models.ForeignKey(help_text='...', on_delete=django.db.models.deletion.CASCADE, to='django_hstl.bed', verbose_name='BedID')),
            ],
        ),
    ]
