# Generated by Django 6.0.2 on 2026-05-13 14:50

import django.db.models.deletion
import django_hstl.valids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_hstl', '0003_room_bed_complaint_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='myuser',
            field=models.OneToOneField(blank=True, help_text='...', limit_choices_to={'is_active': True, 'is_staff': False, 'is_superuser': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='StudentID'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price of the Room', max_digits=10, validators=[django_hstl.valids.validate_price], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('A1', 'AC Single'), ('N1', 'Non-AC Single'), ('A2', 'AC Double'), ('N2', 'Non-AC Double'), ('A3', 'AC Triple'), ('N3', 'Non-AC Triple'), ('A4', 'AC Quadruple'), ('N4', 'Non-AC Quadruple')], help_text='Select a room type', max_length=2, verbose_name='Room Type'),
        ),
    ]
