# Generated by Django 6.0.2 on 2026-05-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_hstl', '0004_alter_bed_myuser_alter_room_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='admin_remarks',
            field=models.TextField(blank=True, help_text='Admin remark on Complaint', max_length=500, null=True, verbose_name='Admin Rmarks'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(help_text='Please tell us more about issue', max_length=500, verbose_name='Description'),
        ),
    ]
